### ISSUE TITLE
Consider having pyramid_swagger handle basic primitive conversion in query/path/bodies

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#22]
One major source of repetitive busywork in Pyramid views is casting query and path parameters into their proper type in your view (e.g. /user/1 will appear in Pyramid's matchdict as a string, not an integer). A service's Swagger spec has the necessary context to do this at the tween level, and in fact we already have the mapping available for doing our own validation. For query bodies, we should just be strongly recommending JSON everywhere as it will handle its own typecasting.

This would simplify boilerplate in views which use these parameters, which often looks like:

``` python
@view_config('user_search')  # Serves /user/{id}/items?count=5&start=0
def user_search_view(request):
    id = int(request.matchdict['id'])
    start = int(request.params['start'])
    count = int(request.params['count'])
    user_item_search(id, count, start)
```

Would offering casting for incoming query and path parameters be of interest? The proposal would be to only support the types defined by Swagger, with no plans to implement richer types (that is up to service authors to do separately). As always, we can make the feature controlled by a setting in your Pyramid app's config.

**Comment by dnephin** [comment]
Looking at the code, I think the casting to type is already being done (for the most part, maybe not date/date-time), it just needs to be added to the request somewhere.  With gluapy I added a dict at `request.data` where the keys were the parameter names, and the values were the already casted python values.  I liked that setup a lot and would be interested in doing the same here.

`request.data` could be some other property, maybe `request.swagger_data` ? Parameter names are unique so there should be no chance of conflicts in the dict.

I like this setup because you still get access to the raw request values in their usual place, and you don't have to deal with extracting values from different parts of the request object. They're all available in the same dict.

**Comment by striglia** [comment]
Good call, https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#524-parameter-object definitely requires the parameter names to be unique.

Yeah this honestly feels like a relatively easy win, particularly if we make it opt-in by not mutating the core request data like you propose. It can pull things off the wire and instantiate basic python types, then library users are free to build different DTOs, use the data directly, whatever.

**Comment by sabrina261087** [comment]
@view_config(route_name="findPetsByStatus")
def findPetsByStatus(request):
    # Returns thing_id as an int (assuming the swagger type is integer)
    thing_id = request.swagger_data['petId']
    return {thing_id}

I tested this method http://localhost:6543/pet/findByStatus?status=available/ but I get 
'available/' is not one of ['available', 'pending', 'sold'] Failed validating 'enum' in schema['properties']['status']: {'allowMultiple': True, 'defaultValue': 'available', 'description': 'Status values that need to be considered for filter', 'enum': ['available', 'pending', 'sold'], 'name': 'status', 'paramType': 'query', 'required': True, 'type': 'string'} On instance['status']: 'available/'

**Comment by striglia** [comment]
Please open new tickets for bugs you find (like you did in #108)
