### ISSUE TITLE
Serving API explorer in `api_docs`

### ISSUE THREAD

**Issue by ergo** [striglia/pyramid_swagger#225]
Hi,

I've added pyramid swagger to my project, I'm trying to figure out how to embed and serve API explorer for the schema inside the application, as I understand `api_docs` dir serves this purpose but it seems to be undocumented.

**Comment by striglia** [comment]
By "API explorer" do you mean something like https://swagger.io/swagger-ui/?

Pyramid-swagger is capable of (and does by default) serving your API spec over HTTP, but there's no built in support for an explorable UI for it. The typical setup is you would point a UI tool at your service's HTTP spec (or copy the raw files into the UI).

The api_docs directory  is just the default location pyramid-swagger looks for your spec.

**Comment by ergo** [comment]
Yes, thats what I was thinking, if there is a good way to embed `swagger-ui` serving, that would be quite a nice feature.

**Comment by striglia** [comment]
Ah, I think that's fairly far outside the scope of how I imagined the project. I think any integration there would be forced to duplicate all the hard work swagger-ui has put in, and you're probably better off just composing the two projects instead of trying to combine them.

That said, if you become aware of a way to compose them nicely (e.g. some manner of pyramid plugin perhaps?) please do comment here, I'm sure you're not the only one who's wished for this :)

**Comment by ergo** [comment]
> integration there would be forced to duplicate all the hard work swagger-ui has put in, 

I saw some plugins for flask that did this, basicly what they did they shipped static files for swagger UI and replaced paths to make them serve correctly.

> I think that's fairly far outside the scope of how I imagined the project.

Is there a document that defines the scope so we can have a discussion about possible features.

**Comment by ergo** [comment]
@striglia If I would make a PR with this feature would you accept it, I plan to work on this soon.
