### ISSUE TITLE
ReadTheDocs build broken

### ISSUE THREAD

**Issue by striglia** [striglia/pyramid_swagger#92]
Probably since we added the pretty tree formatting on http://pyramid-swagger.readthedocs.org/en/latest/configuration.html#generate-resource-listing

See https://readthedocs.org/builds/pyramid-swagger/2397492/

**Comment by dnephin** [comment]
It looks like the error for the html docs is unrelated to that:
https://readthedocs.org/builds/pyramid-swagger/2499938/

The new version of sphinx raises an warning if you use `default` (and since sphinx warnings are treated like errors in `pyramid_swagger` it was raiding an error), but I guess readthedocs isn't using the new version of sphinx, so it doesn't have `classic`.

**Comment by dnephin** [comment]
Found the issue https://github.com/rtfd/readthedocs.org/issues/1202

**Comment by dnephin** [comment]
Maybe just pointing it at a requirements.txt in advanced settings will fix it?

**Comment by striglia** [comment]
Ah good catch. Yeah seems like we want to be pinning a version of sphinx if we aren't already. Hopefully there's a way to do that in-repo and have RTD respect it.

**Comment by shabda** [comment]
You can work around this like this

https://github.com/shabda/pysaml2/blob/master/doc/conf.py#L95

**Comment by striglia** [comment]
Still busted on the Unicode issues. See https://github.com/rtfd/readthedocs.org/issues/416

**Comment by striglia** [comment]
Finally up to date http://pyramid-swagger.readthedocs.org/en/latest/changelog.html
